#!/bin/bash
mv /tmp/betty /tmp/my_first_directory
~
~
~
~
~
~
~
~
~
~
"7-movethatfile" [New File]                                   0,0-1         All

~
~
~
~
~
~
~
~
~
~
"7-movethatfile" [New File]                                   0,0-1         All

